import { useState, useEffect } from 'react'
import { aiApi, ApprovalItem } from '@/features/ai-workforce/services/ai.api'

export function AIApprovalsPage() {
  const [approvals, setApprovals] = useState<ApprovalItem[]>([])
  const [loading, setLoading] = useState(true)

  const fetchApprovals = async () => {
    setLoading(true)
    try {
      const data = await aiApi.getApprovals()
      setApprovals(data || [])
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchApprovals()
  }, [])

  const handleApprove = async (id: string) => {
    try {
      await aiApi.approveAction(id)
      fetchApprovals()
    } catch (e) {
      console.error(e)
    }
  }

  const handleReject = async (id: string) => {
    try {
      await aiApi.rejectAction(id)
      fetchApprovals()
    } catch (e) {
      console.error(e)
    }
  }

  return (
    <div className="space-y-6 animate-fade-in max-w-4xl mx-auto">
      {/* Header */}
      <div className="glass-panel p-6 rounded-3xl border border-outline-variant/40 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="icon text-warning text-xl">shield</span>
            <span className="text-label-sm font-semibold uppercase tracking-wider text-warning">
              Human-In-The-Loop Governance
            </span>
          </div>
          <h1 className="text-headline-md font-bold text-on-surface">Human Approvals Guard Queue</h1>
          <p className="text-body-sm text-on-surface-variant">
            Review and approve high-impact actions generated by AI agents before execution.
          </p>
        </div>
      </div>

      {/* Approvals List */}
      <div className="space-y-4">
        {loading ? (
          <div className="glass-panel p-8 text-center rounded-2xl text-on-surface-variant">
            <span className="icon text-2xl animate-spin text-primary block mb-2">sync</span>
            Loading approvals queue...
          </div>
        ) : approvals.length === 0 ? (
          <div className="glass-panel p-12 text-center rounded-2xl text-on-surface-variant space-y-2">
            <span className="icon text-4xl text-secondary block">verified_user</span>
            <div className="text-body-md font-bold text-on-surface">Queue Clear!</div>
            <p className="text-body-sm">All AI actions have been reviewed or auto-approved.</p>
          </div>
        ) : (
          approvals.map((item) => (
            <div key={item.id} className="glass-panel p-6 rounded-2xl border border-warning/30 space-y-4 relative">
              <div className="flex items-center justify-between border-b border-outline-variant/20 pb-3">
                <div className="flex items-center gap-3">
                  <span className="status-badge error uppercase">{item.actionType}</span>
                  <span className="text-body-sm font-semibold text-on-surface">{item.agentName}</span>
                </div>
                <span className="text-label-md font-mono text-secondary">
                  Confidence: {Math.round(item.confidenceScore * 100)}%
                </span>
              </div>

              <div>
                <div className="text-label-md font-semibold uppercase text-on-surface-variant mb-1">Target Account / Lead</div>
                <div className="text-body-md font-bold text-on-surface mb-2">{item.target}</div>

                {item.payload.subject && (
                  <div className="p-3 rounded-xl bg-surface-container-high text-body-sm text-on-surface font-medium mb-2">
                    Subject: {item.payload.subject}
                  </div>
                )}

                <div className="p-3 rounded-xl bg-surface-container-low text-body-sm text-on-surface-variant italic">
                  "{item.payload.preview || item.payload.reason}"
                </div>
              </div>

              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  onClick={() => handleReject(item.id)}
                  className="btn-ghost py-2 px-5 text-xs text-error border-error/30 hover:bg-error/10"
                >
                  Reject Action
                </button>

                <button
                  onClick={() => handleApprove(item.id)}
                  className="btn-primary py-2 px-6 text-body-sm font-semibold flex items-center gap-1.5"
                >
                  <span className="icon text-base">check_circle</span>
                  <span>Approve & Execute</span>
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}
